# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        # Bỏ dòng cache: 'npm' vì không có file lock ở thư mục gốc

    # Backend setup & run
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm install
        npm run start &
      
    # Frontend setup & run
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm run dev &
        
    # Keep the workflow running for a while
    - name: Keep alive
      run: sleep 30
